


/*
window.addEventListener('load', function(e) {
  document.querySelector('#test').innerHTML = 'resident_class';
}, false);

*/

// Generated by CoffeeScript 1.6.2
/*(function() {
  var Resident;

  Resident = (function() {
    function Resident() {}

    Resident.prototype.hey = function(what) {
      return 'Whatever.';
    };

    return Resident;

  })();

  module.exports = Resident;

}).call(this);
*/



// global vars
var selected_user = new Resident();



// list of reasons for not being home
var reason_list = [
    "None",
    "Food",
    "Church",
    "Meeting",
    "Probation",
    "Court",
    "Work",
    "Other"
];




// constructor null
function Resident(){
    this.id_num = null;
    this.firstName = null;
    this.lastName = null;
    this.isPresent = true;
    this.reasonNotPresent = null;
}// end null def


// constructer overloaded
function Resident(id_num,f_name,l_name,present_bool, reason){
    this.id_num = id_num;
    this.firstName = f_name;
    this.lastName = l_name;
    this.isPresent = present_bool;
    if (reason != null){
        this.reasonNotPresent = reason;
    } else {
        this.reasonNotPresent = null;
        }
}// end overload def


Resident.prototype.setReasonNotPresent = function(str){
    if (str.length > 0){
        this.reasonNotPresent = str;
        return true;
    } else {
        this.reasonNotPresent = null;
        return false;
    }
}


Resident.prototype.getReasonNotPresent = function(){
    return this.reasonNotPresent;
}




Resident.prototype.setIsPresent = function(bool_val){
    this.isPresent = bool_val;
}



// methods
Resident.prototype.getIsPresent = function(){
    if (this.isPresent == true){
        alert("Present")
        return true;
    }
    return false;
}



// methods
Resident.prototype.getFullName = function(){
    return this.firstName + " " + this.lastName;
}


// GLOBAL FUNCTIONS !!!!





// check user input
function checkAnswer(num, list){

    for (i = 0; i < list.length; i++) {
        if (num == list[i].id_num){
            //alert("Correct!")
            selected_user = list[i];
            return true;
        }
    }
    return false;

}// end check answer def









function main(){

   var user_list = [];


   var userObject = new Resident(
        10,
        "Eric",
        "Phung",
        false,
        null
    );


    user_list.push(userObject);

    var answer = prompt("Enter your ID");

    if (checkAnswer(answer, user_list) == true) {
        alert("Correct " + selected_user.firstName)
    }


}// end main def





function getDatabaseResidents (content) {

    // create a virtual db
    var list = [];
    console.log("\n * Creating Database * \n");

    // construct db resident objects from json
    content.residents.forEach(function (item) {
        list.push(new Resident(
            item.id_num,
            item.firstName,
            item.lastName,
            item.isPresent,
            item.reasonNotPresent
        ));
    })
    console.log("\n * Finished Database * \n");

    return list;

}// end set up db def






console.log("Hi There")








